### ISSUE TITLE
Saving files as MP4 Instead

### ISSUE THREAD

**Issue by ejuarezg** [irahorecka/youtube2audio#8]
Hi,

Really cool project by the way.

I was editing the code and trying to find a way to save the downloaded files as MP4 instead (the way that they are downloaded). I've managed to tweak the code in `download_youtube.py`. The only thing left to do is to add a simple check box to the GUI to allow the user to save as MP3 or MP4. How would I accomplish? The value of this boolean variable would passed into the `thread_query_youtube` function as an argument.

I'd appreciate any help or direction you can give me.

If I get this working, I can do a pull request if you are interested in this functionality.

**Comment by irahorecka** [comment]
Hey Ezequiel, this is a great idea! 

Do you have QT Designer? This is a desktop application to quickly generate a UI (add buttons, labels, tables, etc) , which can compile down to python code with a simple command:
$ pyuic5 some_ui.ui -o some_ui.py

Anyways, what if we added a checkbox that says save MP4. Like you said, this can be a boolean. If you look at line 419 in main.py, you’ll see that I purposefully remove the mp4 files after conversion to mp3 is complete (shutil.rmtree(mp4_path)  # remove mp4 dir).

 Now this may not be the best design idea, but if this is triggered on a boolean conditional, then we can either keep or remove this directory.

If you make a cool patch, feel free to submit a PR - always looking to collaborate!

- Ira

**Comment by ejuarezg** [comment]
Awesome! I'll tinker with QT Designer and see what I can put together. Thanks!

**Comment by irahorecka** [comment]
merged PR
